cumbia-hdb: CuHdbFetchActivity Class Reference
CuHdbFetchActivity Class Reference
an activity to periodically read from Tango. Implements CuContinuousActivity
#include <cuhdbfetchactivity.h>
Public Types
enum Type { CuHdbFetchActivityType = CuActivity::User + 7 }
defines the Type of the activity, returned by getType
Public Member Functions
CuHdbFetchActivity (const CuData &token, HdbXSettings *hdbxs)
the class constructor that sets up a Tango polling activity
~CuHdbFetchActivity ()
the class destructor
bool matches (const CuData &token) const
returns true if the passed token's device activity and period values matche this activity token's device and activity and period values.
void event (CuActivityEvent *e)
int getType () const
returns the type of the polling activity
void onSourceProgressUpdate (const char *name, double percent)
void onExtractionFinished (int totalRows, double elapsed)
void onSourceExtractionFinished (const char *name, int totalRows, double elapsed)
Protected Member Functions
void init ()
the implementation of the CuActivity::init hook
void execute ()
the implementation of the CuActivity::execute hook
void onExit ()
the implementation of the CuActivity::onExit hook
Detailed Description
an activity to periodically read from Tango. Implements CuContinuousActivity
Implementing CuActivity, the work is done in the background by the three methods
init
execute
onExit
They are called from a separate thread. In cumbia-tango, threads are grouped by device.
Apart from the three execution hooks listed above, some other methods have been written to comply with the CuActivityInterface:
getType, returning CuEventActivityType
event, to receive CuActivityEvent events
matches, that returns true if the input token represents an activity like this
repeat, that indicates whether or not execute has to be called again
Note
CuHdbGenActivity must stay in execution (must not exit) until CuTReader is stopped (CuTReader::stop). For this reason, CuAUnregisterAfterExec is set to false. When the Tango device is not defined into the database (in CuHdbGenActivity::execute the Tango::DeviceProxy is NULL) the repeat time is set to a negative number. This suspends the continuous activity without exiting. It will be asked to exit from CuTReader::stop through Cumbia::unregisterActivity.
CuADeleteOnExit is left to true in order to let the activity be deleted by CuThread after onExit.
This combination of the flags guarantees the availability of the CuHdbGenActivity when CuTReader::stop is called (activity will be either executing the polling loop or suspended) and lets CuTReader not worry about the activity deletion.
See also
CuTReader
CuTReader::stop
Member Enumeration Documentation
Type
enum CuHdbFetchActivity::Type
defines the Type of the activity, returned by getType
Enumerator
CuHdbFetchActivityType
Constructor & Destructor Documentation
CuHdbFetchActivity()
CuHdbFetchActivity::CuHdbFetchActivity (const CuData & token, HdbXSettings * hdbxs)
the class constructor that sets up a Tango polling activity
Parameters
token a CuData that will describe this activity
df a pointer to a CuDeviceFactoryService that is used by init and onExit to create/obtain and later get rid of a Tango device, respectively
argins input arguments that can optionally be passed to Tango commands as argins
notes
the default polling period is 1000 milliseconds
if the "period" key is set on the token, then it is converted to int and it will be used to set up the polling period
CuADeleteOnExit is active.
CuAUnregisterAfterExec is disabled because if the Tango device is not defined into the database the poller is not started and the activity is suspended (repeat will return -1).
References CuHdbActivityPrivate::errCnt, CuHdbActivityPrivate::exec_cnt, CuHdbActivityPrivate::exiting, CuHdbActivityPrivate::hdb_extractor, CuHdbActivityPrivate::hdbx_s, CuHdbActivityPrivate::label, CuHdbActivityPrivate::other_thread_id, and CuHdbActivityPrivate::repeat.
~CuHdbFetchActivity()
CuHdbFetchActivity::~CuHdbFetchActivity ()
the class destructor
deletes the internal data
Member Function Documentation
event()
void CuHdbFetchActivity::event (CuActivityEvent * e)
execute()
void CuHdbFetchActivity::execute () protected
the implementation of the CuActivity::execute hook
This is repeatedly called in the CuActivity's thread of execution, according to the period chosen for the reader.
See also CuActivity::execute and CuEventActivity
References CuHdbActivityPrivate::exec_cnt, CumbiaHdbWorld::extract_data(), CuHdbActivityPrivate::hdb_extractor, CumbiaHdbWorld::hdbppConfQuery(), CuHdbActivityPrivate::hdbx_s, CumbiaHdbWorld::isHdbpp(), and CuHdbActivityPrivate::my_thread_id.
getType()
int CuHdbFetchActivity::getType () const
returns the type of the polling activity
Returns
the CuHdbGenActivityType value defined in the Type enum
References CuHdbFetchActivityType.
init()
void CuHdbFetchActivity::init () protected
the implementation of the CuActivity::init hook
This is called in the CuActivity's thread of execution.
See also CuActivity::init, execute and onExit
References CuHdbActivityPrivate::my_thread_id, CuHdbActivityPrivate::other_thread_id, and CuHdbActivityPrivate::thread_token.
matches()
bool CuHdbFetchActivity::matches (const CuData & token) const
returns true if the passed token's device activity and period values matche this activity token's device and activity and period values.
Parameters
token a CuData containg key/value pairs of another activity's token
Returns
true if the input token's "period" device and activity values match this token's "period" device and activity values
Two CuHdbGenActivity match if they refer to the same device and have the same period.
onExit()
void CuHdbFetchActivity::onExit () protected
the implementation of the CuActivity::onExit hook
This is called in the CuActivity's thread of execution.
client reference counter is decreased on the TDevice (TDevice::removeRef)
CuDeviceFactoryService::removeDevice is called to remove the device from the device factory if the reference count is zero
the result of the operation is published to the main thread through publishResult
See also CuActivity::onExit
References CuHdbActivityPrivate::exiting, CuHdbActivityPrivate::hdb_extractor, and CuHdbActivityPrivate::my_thread_id.
onExtractionFinished()
void CuHdbFetchActivity::onExtractionFinished (int totalRows, double elapsed)
onSourceExtractionFinished()
void CuHdbFetchActivity::onSourceExtractionFinished (const char * name, int totalRows, double elapsed)
References CumbiaHdbWorld::extract_data(), and CuHdbActivityPrivate::hdb_extractor.
onSourceProgressUpdate()
void CuHdbFetchActivity::onSourceProgressUpdate (const char * name, double percent)
References CumbiaHdbWorld::extract_data(), and CuHdbActivityPrivate::hdb_extractor.
The documentation for this class was generated from the following files:
cuhdbfetchactivity.h
cuhdbfetchactivity.cpp