cumbia-hdb: CuHdbActionFactoryI Class Reference
CuHdbActionFactoryI Class Reference abstract
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
#include <cuhdbactionfactoryi.h>
Public Member Functions
virtual ~CuHdbActionFactoryI ()
virtual CuHdbActionI * create (const std::string &source, CumbiaHdb *ct) const =0
virtual CuHdbActionI::Type getType () const =0
Return the type of action that the factory creates.
Detailed Description
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
Notable implementations
CuTangoReaderFactory
CuTangoWriterFactory
CuTangoAttConfFactory
Constructor & Destructor Documentation
~CuHdbActionFactoryI()
virtual CuHdbActionFactoryI::~CuHdbActionFactoryI () inline virtual
Member Function Documentation
create()
virtual CuHdbActionI* CuHdbActionFactoryI::create (const std::string & source, CumbiaHdb * ct) const pure virtual
Pure virtual method that must be implemented by subclasses to return a valid CuTangoActionI instance.
Parameters
source a string identifying a source to connect to
ct a pointer to a CumbiaHdb instance
Implemented in CuHdbActionReaderFactory.
Referenced by CuHdbActionFactoryService::registerAction().
getType()
virtual CuHdbActionI::Type CuHdbActionFactoryI::getType () const pure virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implemented in CuHdbActionReaderFactory.
Referenced by CumbiaHdb::addAction(), and CuHdbActionFactoryService::registerAction().
The documentation for this class was generated from the following file:
cuhdbactionfactoryi.h