cumbia-hdb: HdbSource Class Reference
HdbSource Class Reference
#include <hdb_source.h>
Public Types
enum Type { Invalid = -1, DataFetch = 0, FindSources, Query }
Public Member Functions
HdbSource ()
HdbSource (const std::string &s)
HdbSource constructor.
HdbSource (const HdbSource &other)
string getName () const
get the complete source, including the domain, "hdb://", if specified
string getDomain () const
HdbSource & operator= (const HdbSource &other)
bool operator== (const HdbSource &other) const
bool isValid () const
std::string error () const
std::string start_date () const
std::string stop_date () const
std::string find_pattern () const
std::string query () const
Type getType () const
Static Public Member Functions
static const char * hdb_source_regexp ()
Member Enumeration Documentation
Type
enum HdbSource::Type
Enumerator
Invalid
DataFetch
FindSources
Query
Constructor & Destructor Documentation
HdbSource() [1/3]
HdbSource::HdbSource ()
HdbSource() [2/3]
HdbSource::HdbSource (const std::string & s)
HdbSource constructor.
Accepted syntax
[hdb://]domain/family/device/attribute(start_date, stop_date) start_date: YYYY-MM-dd hh:mm:ss e.g. 2019-06-21 10:00:00 stop_date: YYYY-MM-dd hh:mm:ss e.g. 2019-06-21 10:00:00 Get data within start_date and stop_date
[hdb://]domain/family/device/attribute(date) date YYYY-MM-dd hh:mm:ss e.g. 2019-06-21 10:00:00 Get the value at the given date in the past
hdb://find/pattern find sources matching pattern
hdb://query/sql_query perform the specified query to the database
Parameters
s a string conforming to the accepted forms
References hdb_src_regex.
HdbSource() [3/3]
HdbSource::HdbSource (const HdbSource & other)
Member Function Documentation
error()
string HdbSource::error () const
find_pattern()
string HdbSource::find_pattern () const
getDomain()
string HdbSource::getDomain () const
getName()
string HdbSource::getName () const
get the complete source, including the domain, "hdb://", if specified
Returns
the complete source passed to the HdbSource constructor
Referenced by CuHdbActionReader::getToken(), and CuHdbActionReader::onResult().
getType()
HdbSource::Type HdbSource::getType () const
References DataFetch, FindSources, Invalid, and Query.
hdb_source_regexp()
const char * HdbSource::hdb_source_regexp () static
References hdb_src_regex.
Referenced by CumbiaHdbWorld::CumbiaHdbWorld().
isValid()
bool HdbSource::isValid () const
Referenced by CumbiaHdbWorld::source_valid().
operator=()
HdbSource & HdbSource::operator= (const HdbSource & other)
operator==()
bool HdbSource::operator== (const HdbSource & other) const
query()
string HdbSource::query () const
start_date()
string HdbSource::start_date () const
stop_date()
string HdbSource::stop_date () const
The documentation for this class was generated from the following files:
hdb_source.h
hdb_source.cpp