cumbia-hdb: CuHdbActionReader Class Reference
CuHdbActionReader Class Reference
Low level class to read tango attributes and commands with output arguments.
#include <cuhdbactionreader.h>
Public Types
enum RefreshMode { HdbGenerator = 0 }
The reader refresh mode.
Public Types inherited from CuHdbActionI
enum Type {
HdbFetch = 0, Writer, AttConfig, DbReadProp,
DbWriteProp
}
Public Member Functions
CuHdbActionReader (const HdbSource &src, CumbiaHdb *ct)
~CuHdbActionReader ()
void onProgress (int step, int total, const CuData &data)
progress notification callback
void onResult (const CuData &data)
void onResult (const std::vector< CuData > &datalist)
void setOptions (const CuData &options)
CuData getToken () const
returns the CuData storing the token that identifies this action
HdbSource getSource () const
CuHdbActionI::Type getType () const
returns the type of CuHdbActionI implemented
void sendData (const CuData &data)
Send data with parameters to configure the reader.
void getData (CuData &inout) const
Get parameters from the reader.
void start ()
the method where activities are created and registered
void stop ()
the method where activities are unregistered from Cumbia
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
bool exiting () const
returns true if the action has been stopped and it's exiting
void setHdbXSettings (HdbXSettings *hdbs)
set HdbXSettings
Public Member Functions inherited from CuHdbActionI
CuHdbActionI ()
virtual ~CuHdbActionI ()
virtual destructor, to make compilers happy
Detailed Description
Low level class to read tango attributes and commands with output arguments.
This class implements the CuHdbActionI interface, which in turn implements CuThreadListener.
Programmers of graphical interfaces should employ cumbia-tango-controls CuTControlsReader higher level class to create and communicate with CuTReader.
Function
Instantiates and registers (i.e. starts) either a CuEventActivity or a CuPollingActivity, according to the desired RefreshMode. If the CuEventActivity fails subscribing to the Tango event system, it is replaced by CuPollingActivity (in CuTReader::onResult). In that case, no error event is delivered to CuDataListeners.
Note
CuTReader holds a pointer to the current activity (CuTReaderPrivate: current_activity). Activity and CuTReader's life are independent from each other: if the CuActivity::CuADeleteOnExit flag is active (as in CuPollingActivity), the activity is deleted by CuThread.
Important
As a consequence of the note above, activities must not exit before CuTReader::stop is called. The proper way to stop the activity associated to the reader is through CuTReader::stop.
Member Enumeration Documentation
RefreshMode
enum CuHdbActionReader::RefreshMode
The reader refresh mode.
Each refresh mode reflects the way a tango attribute can be read. Commands are always polled with a given period (default: 1000ms). The preferred read mode for attributes is by events (ChangeEventRefresh). If they are not available, the second choice mode is PolledRefresh.
Manual mode starts (or switches to) a polling activity that is immediately paused. A specific argument must be specified to sendData to trigger a manual reading.
Enumerator
HdbGenerator
Constructor & Destructor Documentation
CuHdbActionReader()
CuHdbActionReader::CuHdbActionReader (const HdbSource & src, CumbiaHdb * ct)
References CuHdbActionReaderPrivate::cumbia_hdb, CuHdbActionReaderPrivate::exit, CuHdbActionReaderPrivate::hdb_src, and CuHdbActionReaderPrivate::hdbx_settings.
~CuHdbActionReader()
CuHdbActionReader::~CuHdbActionReader ()
Member Function Documentation
addDataListener()
void CuHdbActionReader::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::listeners.
dataListenersCount()
size_t CuHdbActionReader::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::listeners.
exiting()
bool CuHdbActionReader::exiting () const virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::exit.
getData()
void CuHdbActionReader::getData (CuData & d_inout) const virtual
Get parameters from the reader.
Parameters
d_inout a reference to a CuData bundle containing the parameter names as keys. getData will associate the values to the keys. Unrecognized keys are ignored.
Valid keys
"period": returns an int with the polling period
"refresh_mode": returns a CuHdbActionReader::RefreshMode that can be converted to int
"mode": returns a string representation of the CuHdbActionReader::RefreshMode
See also
sendData
Implements CuHdbActionI.
getSource()
HdbSource CuHdbActionReader::getSource () const virtual
returns the tango source (TSource)
Returns
a TSource object that describes the Tango source
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::hdb_src.
getToken()
CuData CuHdbActionReader::getToken () const virtual
returns the CuData storing the token that identifies this action
Returns
a CuData with the following key/value pairs
"source" --> the name of the source (string)
"type" --> a constant string: "reader"
Reimplemented from CuHdbActionI.
References HdbSource::getName(), and CuHdbActionReaderPrivate::hdb_src.
getType()
CuHdbActionI::Type CuHdbActionReader::getType () const virtual
returns the type of CuHdbActionI implemented
Returns
one of the values from the Type enum
Implements CuHdbActionI.
References CuHdbActionI::HdbFetch.
Referenced by onResult().
onProgress()
void CuHdbActionReader::onProgress (int step, int total, const CuData & data) virtual
progress notification callback
Parameters
step the completed steps in the background
total the total number of steps
data CuData with data from the background activity
The current implementation does nothing
Reimplemented from CuHdbActionI.
onResult() [1/2]
void CuHdbActionReader::onResult (const CuData & data) virtual
Reimplemented from CuHdbActionI.
References CuHdbActionFactoryService::CuHdbActionFactoryServiceType, CuHdbActionReaderPrivate::cumbia_hdb, CuHdbActionReaderPrivate::exit, HdbSource::getName(), getType(), CuHdbActionReaderPrivate::hdb_src, CuHdbActionReaderPrivate::listeners, and CuHdbActionFactoryService::unregisterAction().
onResult() [2/2]
void CuHdbActionReader::onResult (const std::vector< CuData > & datalist) virtual
Reimplemented from CuHdbActionI.
removeDataListener()
void CuHdbActionReader::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::listeners, and stop().
sendData()
void CuHdbActionReader::sendData (const CuData & data) virtual
Send data with parameters to configure the reader.
Parameters
data a CuData bundle with the settings to apply to the reader.
Valid keys
"period": integer. Change the polling period, if the refresh mode is CuHdbActionReader::PolledRefresh
"refresh_mode". A CuHdbActionReader::RefreshMode value to change the current refresh mode.
"read" (value is irrelevant). If the read mode is CuHdbActionReader::PolledRefresh, a read will be performed.
See also
getData
Implements CuHdbActionI.
setHdbXSettings()
void CuHdbActionReader::setHdbXSettings (HdbXSettings * hdbs) virtual
set HdbXSettings
Parameters
hdbs pointer to a previously allocated HdbXSettings
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::hdbx_settings.
setOptions()
void CuHdbActionReader::setOptions (const CuData & options)
References CuHdbActionReaderPrivate::options.
Referenced by CuHdbActionReaderFactory::create().
start()
void CuHdbActionReader::start () virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implements CuHdbActionI.
stop()
void CuHdbActionReader::stop () virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implements CuHdbActionI.
References CuHdbActionReaderPrivate::exit.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cuhdbactionreader.h
cuhdbactionreader.cpp