cumbia-hdb: CumbiaHdb Class Reference
CumbiaHdb Class Reference
#include <cumbiahdb.h>
Public Types
enum Type { CumbiaHdbType = Cumbia::CumbiaUserType + 14 }
enum DbType { Hdb, Hdbpp }
Public Member Functions
CumbiaHdb (CuThreadFactoryImplI *tfi, CuThreadsEventBridgeFactory_I *teb)
~CumbiaHdb ()
CuThreadFactoryImplI * getThreadFactoryImpl () const
CuThreadsEventBridgeFactory_I * getThreadEventsBridgeFactory () const
void setDbProfile (const std::string &db_profile_name)
void setHdbXSettings (HdbXSettings *hdb_settings)
Set custom HdbXSettings.
HdbXSettings * hdbXSettings () const
CuData getDbParams () const
virtual int getType () const
void addAction (const std::string &source, CuDataListener *l, const CuHdbActionFactoryI &f)
void unlinkListener (const string &source, CuHdbActionI::Type t, CuDataListener *l)
CuHdbActionI * findAction (const std::string &source, CuHdbActionI::Type t) const
Member Enumeration Documentation
DbType
enum CumbiaHdb::DbType
Enumerator
Hdb
Hdbpp
Type
enum CumbiaHdb::Type
Enumerator
CumbiaHdbType
Constructor & Destructor Documentation
CumbiaHdb()
CumbiaHdb::CumbiaHdb (CuThreadFactoryImplI * tfi, CuThreadsEventBridgeFactory_I * teb)
References CumbiaHdbPrivate::hdbx_settings.
~CumbiaHdb()
CumbiaHdb::~CumbiaHdb ()
References CumbiaHdbPrivate::hdbx_settings.
Member Function Documentation
addAction()
void CumbiaHdb::addAction (const std::string & source, CuDataListener * l, const CuHdbActionFactoryI & f)
References CuHdbActionI::addDataListener(), CuHdbActionFactoryService::CuHdbActionFactoryServiceType, CuHdbActionFactoryService::findActive(), CuHdbActionFactoryI::getType(), CumbiaHdbPrivate::hdbx_settings, PROFILE_DEFAULT_NAME, CuHdbActionFactoryService::registerAction(), setDbProfile(), CuHdbActionI::setHdbXSettings(), and CuHdbActionI::start().
findAction()
CuHdbActionI * CumbiaHdb::findAction (const std::string & source, CuHdbActionI::Type t) const
References CuHdbActionFactoryService::CuHdbActionFactoryServiceType, and CuHdbActionFactoryService::findActive().
getDbParams()
CuData CumbiaHdb::getDbParams () const
References CumbiaHdbPrivate::db_conn_params.
getThreadEventsBridgeFactory()
CuThreadsEventBridgeFactory_I * CumbiaHdb::getThreadEventsBridgeFactory () const
getThreadFactoryImpl()
CuThreadFactoryImplI * CumbiaHdb::getThreadFactoryImpl () const
getType()
int CumbiaHdb::getType () const virtual
References CumbiaHdbType.
hdbXSettings()
HdbXSettings * CumbiaHdb::hdbXSettings () const
References CumbiaHdbPrivate::hdbx_settings.
setDbProfile()
void CumbiaHdb::setDbProfile (const std::string & db_profile_name)
References CumbiaHdbWorld::getDbProfilesDir(), PROFILES_EXTENSION, and setHdbXSettings().
Referenced by addAction().
setHdbXSettings()
void CumbiaHdb::setHdbXSettings (HdbXSettings * hdb_settings)
Set custom HdbXSettings.
Parameters
hdb_settings a pointer to a previously allocated HdbXSettings object
note
CumbiaHdb takes the ownership of hdb_settings, that is destroyed either after a new call to setHdbXSettings or within CumbiaHdb class destructor.
References CumbiaHdbPrivate::hdbx_settings.
Referenced by setDbProfile().
unlinkListener()
void CumbiaHdb::unlinkListener (const string & source, CuHdbActionI::Type t, CuDataListener * l)
References CuHdbActionFactoryService::CuHdbActionFactoryServiceType, and CuHdbActionFactoryService::find().
The documentation for this class was generated from the following files:
cumbiahdb.h
cumbiahdb.cpp