cumbia-hdb: CumbiaHdbWorld Class Reference
CumbiaHdbWorld Class Reference
#include <cumbiahdbworld.h>
Public Member Functions
CumbiaHdbWorld ()
void setSrcPatterns (const std::vector< std::string > &pat_regex)
std::vector< std::string > srcPatterns () const
bool source_valid (const std::string &s) const
void extract_data (const std::vector< XVariant > &dbdata, CuData &res) const
void extract_data (Result *res, double elapsed, CuData &da)
extract data from a hdbextractor Result and store it into a to a CuData bundle passed as input reference.
std::string getDbProfilesDir () const
size_t rowCount (const CuData &da) const
Returns the row count of the result stored in the input parameter.
size_t slice (const CuData &result, std::vector< std::vector< std::string > > &slices) const
Returns a CuData representing the row r in the result passed as argument.
std::string getValue (const CuData &result, const std::vector< std::vector< std::string > > &slices, size_t row, const char *column_name) const
get the value under row, column from a custom query to the database, after the result has been sliced with CumbiaHdbWorld::slice
std::string hdbppConfQuery (const std::string &att_name) const
bool isHdbpp (const std::string &dbnam) const
Constructor & Destructor Documentation
CumbiaHdbWorld()
CumbiaHdbWorld::CumbiaHdbWorld ()
References HdbSource::hdb_source_regexp().
Member Function Documentation
extract_data() [1/2]
void CumbiaHdbWorld::extract_data (const std::vector< XVariant > & dbdata, CuData & res) const
Referenced by CuHdbFetchActivity::execute(), CuHdbFetchActivity::onSourceExtractionFinished(), and CuHdbFetchActivity::onSourceProgressUpdate().
extract_data() [2/2]
void CumbiaHdbWorld::extract_data (Result * res, double elapsed, CuData & da)
extract data from a hdbextractor Result and store it into a to a CuData bundle passed as input reference.
Parameters
res a Result from DbSchema::query
elapsed the time taken by the query. Will be stored under the "elapsed" key
da a reference to CuData that will contain the keys listed below in case of success.
CuData bundle data keys
The CuData input argument will be filled with the following keys if the DbSchema::query call was successful:
row_count - the number of rows fetched from the database. Use CuVariant::toULongInt (aka size_t) for conversion
column_count - the number of columns selected by the query. Use CuVariant::toULongInt (aka size_t) for conversion
query - the text of the full query submitted
results - a vector of strings (convert with CuData::toStringVector) containing all the rows in sequence, one behind the next.
elapsed - a double representing the elapsed time in seconds.microseconds
Access a field in the CuData "results" value
let data be the name of the CuData input parameter to extract_data
check with data["row_count"] the number of fetched rows (use toULongInt() for conversion)
let size_t row be less than data["row_count"].toULongInt()
let size_t col be less than data["column_count"].toULongInt()
size_t row = 10;
size_t col = 0;
size_t columns = da["column_count"].toULongInt();
// rows are enqueued in da["results"] one behind the next
size_t column_offset = row * columns;
const std::vector<std::string> values = da["results"].toStringVector();
std::string myvalue = values[column_offset + col];
getDbProfilesDir()
std::string CumbiaHdbWorld::getDbProfilesDir () const
References PROFILES_DIR.
Referenced by CumbiaHdb::setDbProfile().
getValue()
std::string CumbiaHdbWorld::getValue (const CuData & result, const std::vector< std::vector< std::string > > & slices, size_t row, const char * column_name) const
get the value under row, column from a custom query to the database, after the result has been sliced with CumbiaHdbWorld::slice
Parameters
result the result from a DbSchema::query (hdbextractor lib)
slices vector of rows (one row is a vector of strings) previously sliced with CumbiaHdbWorld::slice
row the row you want to access
column_name the name of the column you want to access
Returns
the value, as string, under row, column
Note
The input argument must be a valid result from a DbSchema::query call. A valid result will contain the following keys:
row_count
column_count
query
results
as compiled by CumbiaHdbWorld::extract_data(Result *res, double elapsed, CuData& da)
Check the result size greater than zero from CumbiaHdbWorld::slice before calling getValue
hdbppConfQuery()
std::string CumbiaHdbWorld::hdbppConfQuery (const std::string & att_name) const
Referenced by CuHdbFetchActivity::execute().
isHdbpp()
bool CumbiaHdbWorld::isHdbpp (const std::string & dbnam) const
Referenced by CuHdbFetchActivity::execute().
rowCount()
size_t CumbiaHdbWorld::rowCount (const CuData & da) const
Returns the row count of the result stored in the input parameter.
Parameters
da CuData obtained from a generic query expressed with a source like hdb://query/SELECT name from table WHERE field='abc'
Returns
the row count detected in the input parameter or 0 if the argument does not represent a valid result from a generic hdb query or if there are no rows
setSrcPatterns()
void CumbiaHdbWorld::setSrcPatterns (const std::vector< std::string > & pat_regex)
slice()
size_t CumbiaHdbWorld::slice (const CuData & result, std::vector< std::vector< std::string > > & slices) const
Returns a CuData representing the row r in the result passed as argument.
Parameters
result CuData obtained from a generic query expressed with a source like hdb://query/SELECT name from table WHERE field='abc'
slices a reference to a vector of vector of strings that will contains the slices
Returns
the number of slices or 0 if the result is invalid or empty
source_valid()
bool CumbiaHdbWorld::source_valid (const std::string & s) const
References HdbSource::isValid().
srcPatterns()
std::vector< std::string > CumbiaHdbWorld::srcPatterns () const
The documentation for this class was generated from the following files:
cumbiahdbworld.h
cumbiahdbworld.cpp