cumbia-hdb: CuHdbActionI Class Reference
CuHdbActionI Class Reference abstract
#include <cuhdbactioni.h>
Public Types
enum Type {
HdbFetch = 0, Writer, AttConfig, DbReadProp,
DbWriteProp
}
Public Member Functions
CuHdbActionI ()
virtual ~CuHdbActionI ()
virtual destructor, to make compilers happy
virtual HdbSource getSource () const =0
return a HdbSource object that stores information about the Tango source
virtual Type getType () const =0
returns the type of CuHdbActionI implemented
virtual void addDataListener (CuDataListener *l)=0
insert a CuDataListener to the list of listeners of data updates
virtual void removeDataListener (CuDataListener *l)=0
remove a CuDataListener from the list of listeners of data updates
virtual size_t dataListenersCount ()=0
return the number of registered data listeners
virtual void start ()=0
the method where activities are created and registered
virtual void stop ()=0
the method where activities are unregistered from Cumbia
virtual void sendData (const CuData &data)=0
subclasses will implement the necessary code to set data on themselves or to the activities
virtual void getData (CuData &d_inout) const =0
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
virtual bool exiting () const =0
returns true if the action has been stopped and it's exiting
virtual void setHdbXSettings (HdbXSettings *hdbs)=0
set HdbXSettings
virtual void onProgress (int step, int total, const CuData &data)
virtual void onResult (const CuData &data)
virtual void onResult (const std::vector< CuData > &datalist)
virtual CuData getToken () const
Member Enumeration Documentation
Type
enum CuHdbActionI::Type
Enumerator
HdbFetch
Writer
AttConfig
DbReadProp
DbWriteProp
Constructor & Destructor Documentation
CuHdbActionI()
CuHdbActionI::CuHdbActionI ()
~CuHdbActionI()
virtual CuHdbActionI::~CuHdbActionI () inline virtual
virtual destructor, to make compilers happy
Member Function Documentation
addDataListener()
virtual void CuHdbActionI::addDataListener (CuDataListener * l) pure virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implemented in CuHdbActionReader.
Referenced by CumbiaHdb::addAction().
dataListenersCount()
virtual size_t CuHdbActionI::dataListenersCount () pure virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implemented in CuHdbActionReader.
exiting()
virtual bool CuHdbActionI::exiting () const pure virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implemented in CuHdbActionReader.
getData()
virtual void CuHdbActionI::getData (CuData & d_inout) const pure virtual
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation as input argument. data will contain additional output fields filled in by the method when it returns.
note
getData must be synchronous: it's called with input arguments (d_inout) and they are filled in within the same method in the same thread. Asynchronous data fetch from an activity executed in a separate thread can be accomplished by sendData in combination with CuDataListener::onUpdate. There, received data will have to be recognised as coming from a specific request and treated accordingly.
Implemented in CuHdbActionReader.
getSource()
virtual HdbSource CuHdbActionI::getSource () const pure virtual
return a HdbSource object that stores information about the Tango source
Returns
HdbSource, an object storing information on the Tango source
Implemented in CuHdbActionReader.
getToken()
CuData CuHdbActionI::getToken () const virtual
Reimplemented in CuHdbActionReader.
getType()
virtual Type CuHdbActionI::getType () const pure virtual
returns the type of CuHdbActionI implemented
Returns
one of the values from the Type enum
Implemented in CuHdbActionReader.
onProgress()
void CuHdbActionI::onProgress (int step, int total, const CuData & data) virtual
Reimplemented in CuHdbActionReader.
onResult() [1/2]
void CuHdbActionI::onResult (const CuData & data) virtual
Reimplemented in CuHdbActionReader.
onResult() [2/2]
void CuHdbActionI::onResult (const std::vector< CuData > & datalist) virtual
Reimplemented in CuHdbActionReader.
removeDataListener()
virtual void CuHdbActionI::removeDataListener (CuDataListener * l) pure virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implemented in CuHdbActionReader.
sendData()
virtual void CuHdbActionI::sendData (const CuData & data) pure virtual
subclasses will implement the necessary code to set data on themselves or to the activities
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation
The data can be set locally on the object implementing this interface or can be forwarded to the activity by means of Cumbia::postEvent carrying an argument derived from CuActivityEvent. See CuTReader::sendData for an example
Send a request and receive a response asynchronously
Use sendData in conjunction with CuDataListener::onUpdate, as described in the getData documentation.
Implemented in CuHdbActionReader.
setHdbXSettings()
virtual void CuHdbActionI::setHdbXSettings (HdbXSettings * hdbs) pure virtual
set HdbXSettings
Parameters
hdbs pointer to a previously allocated HdbXSettings
Implemented in CuHdbActionReader.
Referenced by CumbiaHdb::addAction().
start()
virtual void CuHdbActionI::start () pure virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implemented in CuHdbActionReader.
Referenced by CumbiaHdb::addAction().
stop()
virtual void CuHdbActionI::stop () pure virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implemented in CuHdbActionReader.
The documentation for this class was generated from the following files:
cuhdbactioni.h
cuhdbactioni.cpp